# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1br5u601bojQU7OvcHNX7Gsufth0js40U
"""

from setuptools import setup, find_packages

setup(
    name="topsis-decision-analysis",
    version="1.0.0",
    packages=find_packages(),
    install_requires=["pandas", "numpy"],
    entry_points={
        "console_scripts": [
            "topsis=topsis.topsis:main"
        ]
    },
    python_requires=">=3.7",
    author="Sartaj Singh Virdi",
    description="A Python implementation of the TOPSIS method for multi-criteria decision making",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
)